apiVersion: v1
kind: Service
metadata:
  name: student-backend-service
  namespace: student-app
spec:
  type: NodePort
  selector:
    app: student-backend
  ports:
    - port: 8089
      targetPort: 8089
      nodePort: 30089