apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-backend
  namespace: student-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-backend
  template:
    metadata:
      labels:
        app: student-backend
    spec:
      containers:
        - name: student-backend
          image: mayssenj/studentback:latest
          ports:
            - containerPort: 8089
          env:
            - name: SERVER_PORT
              value: "8089"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-service:3306/studentdb?createDatabaseIfNotExist=true
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: root123
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "300m"
              memory: "512Mi"